### PR TITLE
Enabled utf-8 Encoding

### PR DESCRIPTION
**Pull request by harsh52**
Sorry sir,
Last time my email was not correct please consider this.
Thank you.

### CODE REVIEW

**Comment by slavadev** [comment]
Sure

**Comment by slavadev** [comment]
Please create a new PR so your email will be visible

**Comment by harsh52** [comment]
Sir,
You have reverted "Enable utf-8 encoding" ??

**Comment by slavadev** [comment]
Yes, you wanted to have correct email in the commit, but the second(this one) PR didn't add a new commit(cause it was already merged in the previous PR).
As I can't reopen this PR, please create a new PR(same as before), I'll merge it and your email will be visible in there.
Thanks!

**Pull request merged**
